### ISSUE TITLE
$vms.config() deletes the storage

### ISSUE THREAD

**Issue by adyba** [rannn505/ngScopeStorage#1]
I don't really get it. $vms creates 3way binding between scope and [whatever]storage, but all the persistence disappears once the page is reloaded and controller executes $vms.config() again. WTH? The fact that you can't read the vms addressed storage before the $vms.config() makes the Catch22 even more obvious.
I would expect $vms.counter (example ) to remember the number of clicks before the page was reloaded. Am I missing something?

**Comment by rannn505** [comment]
Hey adyba,
First of all thank you for your precious comment,
I promise I'll look deeply into it in the coming days, and if necessary, will implement changes to the module and release a new version.
Thanks again and have a great week :+1:

**Comment by rannn505** [comment]
hey @adyba,
So as I promised, I thought a lot about the things you mentioned in your comment...
Eventually, I decided to put a little upgrade to the module by adding to $vms.config() a property called  "OnReload".
This is an optional Setting determines whether the model will clear the data from storage on page reload or keep it.

Here is an example of how to use it: 
(you can now be sure that $vms.counter from the example will remember the number of clicks before  the page reloads :+1: )

``` javascript
angular.module('app', ['ngScopeStorage'])
    .controller('ctrl', function($scope,$vms){

          $vms.config({scope:$scope, ctrlName:'exampleCtrl', prefix:'exampleApp', onReload:'save'});
          $vms.counter =  parseInt(localStorage.getItem($vms.prefix.concat("counter"))) || 0;
          $vms.increase = function () {
            $vms.counter += 1;
        };
    });
```

I really hope this change answered your expectations...
Thanks again, your comment matters a lot  :)

**Comment by adyba** [comment]
That would be great I always have bunch of settings to keep in sync. But be honest its Sunday night .... Im gonna to test it ... say tomorrow ;)
